baseURL = 'https://srub-sibir.netlify.app'
languageCode = 'ru'
title = 'Сибирский лес - Деревянные дома и бани'
theme = 'custom'

# Настройки сайта
[params]
  description = 'Строительство деревянных домов и бань в Сибири'
  author = 'СрубСибирь'
  email = 'contact@srubsibir.ru'
  phone = '8 800 551 9592'
  phone2 = '8 903 077 0399'
  address = 'Саяногорск, Индустриальная 45'
  showRelatedPosts = true

# Настройки секций - глобальные по умолчанию
[params.sections]
  [params.sections.hero]
    enabled = true  # Показывать слайдер на главной
  
  [params.sections.advantages]
    enabled = true  # Показывать преимущества
  
  [params.sections.projects]
    enabled = true  # Показывать проекты
  
  [params.sections.services]
    enabled = true  # Показывать услуги
  
  [params.sections.technology]
    enabled = true  # Показывать технологии
  
  [params.sections.stages]
    enabled = true  # Показывать этапы
  
  [params.sections.ourJobs]
    enabled = true  # Показывать наши работы
  
  [params.sections.reviews]
    enabled = true  # Показывать отзывы
  
  [params.sections.categories]
    enabled = true  # Показывать категории
  
  [params.sections.contactForm]
    enabled = false # По умолчанию форма выключена
  
  [params.sections.widget]
    enabled = false # Виджеты по запросу
  
  [params.sections.callForm]
    enabled = true  # Форма обратного звонка

# Главное меню навигации

[[menu.main]]
  name = "Услуги"
  url = "/services/"
  weight = 20

[[menu.main]]
  name = "О компании"
  url = "/about/"
  weight = 60

[[menu.main]]
  name = "Проекты"
  url = "/projects/"
  weight = 80

[[menu.main]]
  name = "Контакты"
  url = "/contacts/"
  weight = 110

[[menu.main]]
  name = "Новости"
  url = "/articles/"
  weight = 130

# Остальные настройки...
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]