baseURL = 'http://localhost:1313'
languageCode = 'ru'
title = 'Сибирский лес - Деревянные дома и бани'
theme = 'custom'

# Настройки сайта
[params]
  description = 'Строительство деревянных домов и бань в Сибири'
  author = 'СрубСибирь'
  email = 'contact@srubsibir.ru'
  phone = '8 800 551 9592'
  phone2 = '8 903 077 0399'
  address = 'Саяногорск, Индустриальная 45'
  showRelatedPosts = true

# Главное меню навигации
[[menu.main]]
  name = "Цены"
  url = "/pricing/"
  weight = 10

[[menu.main]]
  name = "Услуги"
  url = "/services/"
  weight = 20

[[menu.main]]
  name = "Дома-бани"
  url = "/houses-baths/"
  weight = 30

[[menu.main]]
  name = "Беседки"
  url = "/gazebos/"
  weight = 40

[[menu.main]]
  name = "Оплата и доставка"
  url = "/payment-delivery/"
  weight = 50

[[menu.main]]
  name = "О нас"
  url = "/about/"
  weight = 60

[[menu.main]]
  name = "Скидки %"
  url = "/discounts/"
  weight = 70

[[menu.main]]
  name = "Проекты"
  url = "/projects/"
  weight = 80

[[menu.main]]
  name = "Срубы домов"
  url = "/house-logs/"
  weight = 90

[[menu.main]]
  name = "Срубы бань"
  url = "/bath-logs/"
  weight = 100

[[menu.main]]
  name = "Контакты"
  url = "/contacts/"
  weight = 110

[[menu.main]]
  name = "Отзывы"
  url = "/reviews/"
  weight = 120

[[menu.main]]
  name = "Статьи"
  url = "/articles/"
  weight = 130

# Дополнительные меню для футера
[[menu.footer]]
  name = "О компании"
  url = "/about/"
  weight = 10

[[menu.footer]]
  name = "Наши услуги"
  url = "/services/"
  weight = 20

[[menu.footer]]
  name = "Проекты"
  url = "/projects/"
  weight = 30

[[menu.footer]]
  name = "Контакты"
  url = "/contacts/"
  weight = 40

# Быстрые ссылки
[[menu.quick]]
  name = "Расчет стоимости"
  url = "/pricing/"
  weight = 10

[[menu.quick]]
  name = "Заказать звонок"
  url = "/callback/"
  weight = 20

[[menu.quick]]
  name = "Наши работы"
  url = "/projects/"
  weight = 30

# Настройки разметки
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    codeFences = true
    guessSyntax = true

# Настройки для Hugo Pipes
[build]
  writeStats = true

# Настройки вывода (для поиска и RSS)
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# Настройки изображений
[imaging]
  quality = 85
  resampleFilter = "lanczos"

# Настройки минификации
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

# Настройки таксономий
[taxonomies]
  tag = "tags"
  category = "categories"
  service = "services"

# Настройки постоянных ссылок
[permalinks]
  articles = "/articles/:year/:month/:title/"
  projects = "/projects/:title/"
  services = "/services/:title/"

# Настройки связанного контента
[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80

# Настройки безопасности
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

# Настройки кэширования
[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "1h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "1h"
  [caches.images]
    dir = ":cacheDir/images"
    maxAge = "1h"

# Дополнительные параметры для разных разделов
[params.sections]
  [params.sections.pricing]
    title = "Наши цены"
    description = "Прозрачные цены на строительство деревянных домов и бань"
  
  [params.sections.services]
    title = "Услуги"
    description = "Полный спектр услуг по деревянному строительству"
  
  [params.sections.houses_baths]
    title = "Дома-бани"
    description = "Комбинированные проекты домов с банными комплексами"
  
  [params.sections.gazebos]
    title = "Беседки"
    description = "Деревянные беседки для отдыха и торжеств"
  
  [params.sections.about]
    title = "О нас"
    description = "История компании и наши достижения"
  
  [params.sections.discounts]
    title = "Скидки и акции"
    description = "Актуальные предложения и скидки"
  
  [params.sections.projects]
    title = "Наши проекты"
    description = "Галерея выполненных работ"
  
  [params.sections.house_logs]
    title = "Срубы домов"
    description = "Готовые срубы для жилых домов"
  
  [params.sections.bath_logs]
    title = "Срубы бань"
    description = "Срубы для бань и саун"
  
  [params.sections.contacts]
    title = "Контакты"
    description = "Как с нами связаться"
  
  [params.sections.reviews]
    title = "Отзывы клиентов"
    description = "Что говорят о нас наши клиенты"
  
  [params.sections.articles]
    title = "Полезные статьи"
    description = "Советы и рекомендации по деревянному строительству"