baseURL = 'http://5.35.124.243/'
languageCode = 'ru'
title = 'Сибирский лес - Деревянные дома и бани'
theme = 'custom'

# Настройки сайта
[params]
  description = 'Строительство деревянных домов и бань в Сибири'
  author = 'СрубСибирь'
  email = 'contact@srubsibir.ru'
  phone = '8 800 551 9592'
  phone2 = '8 903 077 0399'
  address = 'Саяногорск, Индустриальная 45'
  showRelatedPosts = true

# Настройки секций - глобальные по умолчанию
[params.sections]
  [params.sections.hero]
    enabled = true  # Показывать слайдер на главной
  
  [params.sections.advantages]
    enabled = true  # Показывать преимущества
  
  [params.sections.projects]
    enabled = true  # Показывать проекты
  
  [params.sections.services]
    enabled = true  # Показывать услуги
  
  [params.sections.technology]
    enabled = true  # Показывать технологии
  
  [params.sections.stages]
    enabled = true  # Показывать этапы
  
  [params.sections.ourJobs]
    enabled = true  # Показывать наши работы
  
  [params.sections.reviews]
    enabled = true  # Показывать отзывы
  
  [params.sections.categories]
    enabled = true  # Показывать категории
  
  [params.sections.contactForm]
    enabled = false # По умолчанию форма выключена
  
  [params.sections.widget]
    enabled = false # Виджеты по запросу
  
  [params.sections.callForm]
    enabled = true  # Форма обратного звонка

[permalinks]
  projects = "/projects/:section/:slug/"
  blog = "/blog/:year/:month/:slug/"
  services = "/uslugi/:slug/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Главное меню навигации


[[menu.main]]
  name = "Проекты"
  url = "/projects/"
  weight = 10

[[menu.main]]
  name = "Услуги"
  url = "/uslugi/"
  weight = 20

[[menu.main]]
  name = "О компании"
  url = "/about/"
  weight = 30


[[menu.main]]
  name = "Контакты"
  url = "/contacts/"
  weight = 40

[[menu.main]]
  name = "Новости"
  url = "/articles/"
  weight = 50

# Остальные настройки...
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

# Настройки для секции (в разделе [params])
[params.project_page]
  show_breadcrumbs = true
  show_gallery = true
  show_specifications = true
  show_pricing = true
  show_planning = true
  contact_button_text = "Узнать точную цену!"
  plan_button_text = "Посмотреть план"
