baseURL = 'https://srub-sibir.netlify.app'  # ИЗМЕНИТЕ НА ВАШ URL!
languageCode = 'ru'
title = 'Сибирский лес - Деревянные дома и бани'
theme = 'custom'

# Настройки сайта
[params]
  description = 'Строительство деревянных домов и бань в Сибири'
  author = 'СрубСибирь'
  email = 'contact@srubsibir.ru'
  phone = '8 800 551 9592'
  phone2 = '8 903 077 0399'
  address = 'Саяногорск, Индустриальная 45'
  showRelatedPosts = true

# Главное меню навигации
[[menu.main]]
  name = "Цены"
  url = "/pricing/"
  weight = 10

[[menu.main]]
  name = "Услуги"
  url = "/services/"
  weight = 20

[[menu.main]]
  name = "Дома-бани"
  url = "/houses-baths/"
  weight = 30

[[menu.main]]
  name = "Беседки"
  url = "/gazebos/"
  weight = 40

[[menu.main]]
  name = "Оплата и доставка"
  url = "/payment-delivery/"
  weight = 50

[[menu.main]]
  name = "О нас"
  url = "/about/"
  weight = 60

[[menu.main]]
  name = "Скидки %"
  url = "/discounts/"
  weight = 70

[[menu.main]]
  name = "Проекты"
  url = "/projects/"
  weight = 80

[[menu.main]]
  name = "Срубы домов"
  url = "/house-logs/"
  weight = 90

[[menu.main]]
  name = "Срубы бань"
  url = "/bath-logs/"
  weight = 100

[[menu.main]]
  name = "Контакты"
  url = "/contacts/"
  weight = 110

[[menu.main]]
  name = "Отзывы"
  url = "/reviews/"
  weight = 120

[[menu.main]]
  name = "Статьи"
  url = "/articles/"
  weight = 130

# Настройки разметки
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    codeFences = true
    guessSyntax = true

# Настройки для Hugo Pipes
[build]
  writeStats = true

# Настройки вывода
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# Настройки минификации
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false